services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: bbdmspythondb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
